#include "conf.h"
#include "right.h"
#include "tools.h"

#define MODULES_COUNT 13

int nvRightId[][2] =
{
	{MODULE_USER_GROUP,ACTION_RIGHT},
	{MODULE_USER_GROUP,ACTION_NEW},
	{MODULE_USER_GROUP,ACTION_EDIT},
	
	{MODULE_USER,ACTION_NEW},
	{MODULE_USER,ACTION_EDIT},
	{MODULE_USER,ACTION_DELETE},

	{MODULE_AREA,ACTION_NEW},
	{MODULE_AREA,ACTION_EDIT},
	{MODULE_AREA,ACTION_DELETE},

	{MODULE_SEAWAY,ACTION_NEW},
	{MODULE_SEAWAY,ACTION_EDIT},
	{MODULE_SEAWAY,ACTION_DELETE},

	{MODULE_SYMBOL_TYPE,ACTION_NEW},
	{MODULE_SYMBOL_TYPE,ACTION_EDIT},
	{MODULE_SYMBOL_TYPE,ACTION_DELETE},

	{MODULE_ITEM,ACTION_NEW},
	{MODULE_ITEM,ACTION_EDIT},
	{MODULE_ITEM,ACTION_DELETE},

	{MODULE_PICTURE,ACTION_NEW},
	{MODULE_PICTURE,ACTION_EDIT},
	{MODULE_PICTURE,ACTION_DELETE},
	
	{MODULE_SYMBOL,ACTION_NEW},
	{MODULE_SYMBOL,ACTION_EDIT},
	{MODULE_SYMBOL,ACTION_DELETE},
	{MODULE_SYMBOL,ACTION_MANAGEMENT},
	{MODULE_SYMBOL,ACTION_ADD_TO_GROUP},
	
	{MODULE_SYMBOL_GROUP,ACTION_NEW},
	{MODULE_SYMBOL_GROUP,ACTION_EDIT},
	{MODULE_SYMBOL_GROUP,ACTION_DELETE},

	{MODULE_CHARACTERISTIC,ACTION_NEW},
	{MODULE_CHARACTERISTIC,ACTION_EDIT},
	{MODULE_CHARACTERISTIC,ACTION_DELETE},
	
	{MODULE_BASE_STATION,ACTION_NEW},
	{MODULE_BASE_STATION,ACTION_EDIT},
	{MODULE_BASE_STATION,ACTION_DELETE},

};

SModule nvModule[] =
{	
	{MODULE_USER_GROUP,GetMsg(MSG_USER_GROUP)},
	{MODULE_USER,GetMsg(MSG_USER)},
	{MODULE_AREA,GetMsg(MSG_AREA)},
	{MODULE_SEAWAY,GetMsg(MSG_SEAWAY)},
	{MODULE_SYMBOL_TYPE,GetMsg(MSG_SYMBOL_TYPE)},
	{MODULE_ITEM,GetMsg(MSG_ITEMS)},
	{MODULE_PICTURE,GetMsg(MSG_PICTURE)},
	{MODULE_SYMBOL,GetMsg(MSG_SYMBOL)},
	{MODULE_SYMBOL_GROUP,GetMsg(MSG_SYMBOL_GROUP)},
	{MODULE_CHARACTERISTIC,GetMsg(MSG_CHARACTERISTIC)},
	{MODULE_BASE_STATION,GetMsg(MSG_BASE_STATION)},
	{MODULE_SBMS,GetMsg(MSG_SBMS)},
	{MODULE_OPTION,GetMsg(MSG_OPTIONS)}
};

SAction nvAction[] =
{
	{ACTION_NEW,GetMsg(MSG_NEW)},
	{ACTION_EDIT,GetMsg(MSG_EDIT)},
	{ACTION_DELETE,GetMsg(MSG_DELETE)},
//	{ACTION_RIGHT,GetMsg(MSG_RIGHT)},
	{ACTION_MANAGEMENT,GetMsg(MSG_MANAGEMENT)},
	{ACTION_ADD_TO_GROUP,GetMsg(MSG_ADD_TO_GROUP)},
};

const wchar_t *GetModuleName(int id)
{
	return nvModule[id].name;	
}

int GetModuleId(int id)
{
	return nvModule[id].id;	
}
